import type { AirlineSale } from "./types";
import { AirlineScraper } from "./scraper-base";

const MOCK_SALES_DB: Record<string, AirlineSale[]> = {
  ANA: [
    {
      id: "ana-super-value-2026-05",
      airlineCode: "ANA",
      airlineName: "全日本空輸",
      saleName: "ANA スーパーバリュー SALE",
      description:
        "国際線エコノミークラス対象の期間限定セール。東南アジア・欧州路線が最大50%OFF。",
      startDate: "2026-05-10",
      endDate: "2026-05-25",
      bookingDeadline: "2026-05-24",
      travelPeriodStart: "2026-06-01",
      travelPeriodEnd: "2026-09-30",
      routes: [
        { origin: "東京", originCode: "NRT", destination: "バンコク", destinationCode: "BKK", price: 38000, originalPrice: 72000, currency: "JPY", cabin: "Economy", discount: 47, seatsRemaining: 12 },
        { origin: "東京", originCode: "HND", destination: "ニューヨーク", destinationCode: "JFK", price: 128000, originalPrice: 245000, currency: "JPY", cabin: "Business", discount: 48 },
        { origin: "東京", originCode: "NRT", destination: "ロンドン", destinationCode: "LHR", price: 78000, originalPrice: 142000, currency: "JPY", cabin: "Economy", discount: 45, seatsRemaining: 8 },
        { origin: "大阪", originCode: "KIX", destination: "シンガポール", destinationCode: "SIN", price: 42000, originalPrice: 85000, currency: "JPY", cabin: "Economy", discount: 51, seatsRemaining: 5 },
      ],
      sourceUrl: "https://www.ana.co.jp/ja/jp/promotionl/",
      scrapedAt: new Date().toISOString(),
      isActive: true,
    },
    {
      id: "ana-biz-sale-2026-05",
      airlineCode: "ANA",
      airlineName: "全日本空輸",
      saleName: "ビジネスクラス タイムセール",
      description: "ビジネスクラス限定。ハワイ・北米路線が対象。",
      startDate: "2026-05-15",
      endDate: "2026-05-20",
      bookingDeadline: "2026-05-19",
      travelPeriodStart: "2026-07-01",
      travelPeriodEnd: "2026-12-31",
      routes: [
        { origin: "東京", originCode: "HND", destination: "ホノルル", destinationCode: "HNL", price: 185000, originalPrice: 350000, currency: "JPY", cabin: "Business", discount: 47 },
        { origin: "東京", originCode: "NRT", destination: "ロサンゼルス", destinationCode: "LAX", price: 198000, originalPrice: 380000, currency: "JPY", cabin: "Business", discount: 48 },
      ],
      sourceUrl: "https://www.ana.co.jp/ja/jp/promotionl/",
      scrapedAt: new Date().toISOString(),
      isActive: true,
    },
    {
      id: "ana-tabisale-2026-05",
      airlineCode: "ANA",
      airlineName: "全日本空輸",
      saleName: "ANA 旅割タイムセール",
      description: "国内線エコノミークラス対象。北海道・沖縄路線が特別価格。",
      startDate: "2026-05-15",
      endDate: "2026-05-28",
      bookingDeadline: "2026-05-25",
      travelPeriodStart: "2026-06-15",
      travelPeriodEnd: "2026-08-31",
      routes: [
        { origin: "東京", originCode: "HND", destination: "札幌", destinationCode: "CTS", price: 12800, originalPrice: 38000, currency: "JPY", cabin: "Economy", discount: 66, seatsRemaining: 15 },
        { origin: "東京", originCode: "HND", destination: "大阪", destinationCode: "ITM", price: 9800, originalPrice: 28000, currency: "JPY", cabin: "Economy", discount: 65, seatsRemaining: 25 },
      ],
      sourceUrl: "https://www.ana.co.jp/ja/jp/promotionl/",
      scrapedAt: new Date().toISOString(),
      isActive: true,
    },
  ],
  JAL: [
    {
      id: "jal-special-saver-2026-05",
      airlineCode: "JAL",
      airlineName: "日本航空",
      saleName: "JAL スペシャルセーバー",
      description: "欧州・北米路線エコノミークラスが対象のスペシャル運賃。",
      startDate: "2026-05-12",
      endDate: "2026-05-30",
      bookingDeadline: "2026-05-29",
      travelPeriodStart: "2026-06-15",
      travelPeriodEnd: "2026-10-31",
      routes: [
        { origin: "東京", originCode: "HND", destination: "パリ", destinationCode: "CDG", price: 89000, originalPrice: 158000, currency: "JPY", cabin: "Economy", discount: 44, seatsRemaining: 20 },
        { origin: "東京", originCode: "NRT", destination: "ヘルシンキ", destinationCode: "HEL", price: 82000, originalPrice: 148000, currency: "JPY", cabin: "Economy", discount: 45 },
        { origin: "大阪", originCode: "KIX", destination: "ロサンゼルス", destinationCode: "LAX", price: 95000, originalPrice: 168000, currency: "JPY", cabin: "Economy", discount: 43 },
      ],
      sourceUrl: "https://www.jal.co.jp/jp/ja/campaign/",
      scrapedAt: new Date().toISOString(),
      isActive: true,
    },
    {
      id: "jal-sakitoku-2026-05",
      airlineCode: "JAL",
      airlineName: "日本航空",
      saleName: "JAL 先得割引",
      description: "国内線のお得な先得割引。沖縄・鹿児島路線が対象。",
      startDate: "2026-05-16",
      endDate: "2026-06-05",
      bookingDeadline: "2026-06-01",
      travelPeriodStart: "2026-07-01",
      travelPeriodEnd: "2026-09-30",
      routes: [
        { origin: "東京", originCode: "HND", destination: "沖縄", destinationCode: "OKA", price: 15800, originalPrice: 42000, currency: "JPY", cabin: "Economy", discount: 62, seatsRemaining: 8 },
        { origin: "東京", originCode: "HND", destination: "鹿児島", destinationCode: "KOJ", price: 11800, originalPrice: 35000, currency: "JPY", cabin: "Economy", discount: 66, seatsRemaining: 20 },
      ],
      sourceUrl: "https://www.jal.co.jp/jp/ja/campaign/",
      scrapedAt: new Date().toISOString(),
      isActive: true,
    },
  ],
  PCH: [
    {
      id: "peach-mega-2026-05",
      airlineCode: "PCH",
      airlineName: "Peach Aviation",
      saleName: "Peach メガセール",
      description: "全路線対象のメガセール！片道1,990円〜の衝撃価格。",
      startDate: "2026-05-14",
      endDate: "2026-05-16",
      bookingDeadline: "2026-05-16",
      travelPeriodStart: "2026-06-01",
      travelPeriodEnd: "2026-07-31",
      routes: [
        { origin: "大阪", originCode: "KIX", destination: "台北", destinationCode: "TPE", price: 9800, originalPrice: 22000, currency: "JPY", cabin: "Economy", discount: 55, seatsRemaining: 3 },
        { origin: "大阪", originCode: "KIX", destination: "ソウル", destinationCode: "ICN", price: 5980, originalPrice: 15000, currency: "JPY", cabin: "Economy", discount: 60, seatsRemaining: 7 },
        { origin: "東京", originCode: "NRT", destination: "バンコク", destinationCode: "BKK", price: 14800, originalPrice: 32000, currency: "JPY", cabin: "Economy", discount: 54 },
        { origin: "福岡", originCode: "FUK", destination: "上海", destinationCode: "PVG", price: 8800, originalPrice: 19000, currency: "JPY", cabin: "Economy", discount: 54, seatsRemaining: 10 },
        { origin: "大阪", originCode: "KIX", destination: "札幌", destinationCode: "CTS", price: 3490, originalPrice: 18000, currency: "JPY", cabin: "Economy", discount: 81, seatsRemaining: 3 },
      ],
      sourceUrl: "https://www.flypeach.com/campaign",
      scrapedAt: new Date().toISOString(),
      isActive: true,
    },
  ],
  JJP: [
    {
      id: "jetstar-super-star-2026-05",
      airlineCode: "JJP",
      airlineName: "ジェットスター・ジャパン",
      saleName: "スーパースターセール",
      description: "国内線・国際線が対象の72時間限定セール。",
      startDate: "2026-05-13",
      endDate: "2026-05-16",
      bookingDeadline: "2026-05-16",
      travelPeriodStart: "2026-06-01",
      travelPeriodEnd: "2026-08-31",
      routes: [
        { origin: "東京", originCode: "NRT", destination: "マニラ", destinationCode: "MNL", price: 12800, originalPrice: 28000, currency: "JPY", cabin: "Economy", discount: 54 },
        { origin: "大阪", originCode: "KIX", destination: "台北", destinationCode: "TPE", price: 8900, originalPrice: 20000, currency: "JPY", cabin: "Economy", discount: 56 },
        { origin: "東京", originCode: "NRT", destination: "福岡", destinationCode: "FUK", price: 4990, originalPrice: 22000, currency: "JPY", cabin: "Economy", discount: 77, seatsRemaining: 5 },
      ],
      sourceUrl: "https://www.jetstar.com/jp/ja/deals",
      scrapedAt: new Date().toISOString(),
      isActive: true,
    },
  ],
  EK: [
    {
      id: "emirates-global-2026-05",
      airlineCode: "EK",
      airlineName: "エミレーツ航空",
      saleName: "Emirates グローバルセール",
      description: "全クラス対象。ドバイ経由でヨーロッパ・アフリカへ。",
      startDate: "2026-05-10",
      endDate: "2026-06-10",
      bookingDeadline: "2026-06-09",
      travelPeriodStart: "2026-06-15",
      travelPeriodEnd: "2026-12-15",
      routes: [
        { origin: "東京", originCode: "NRT", destination: "ドバイ", destinationCode: "DXB", price: 68000, originalPrice: 125000, currency: "JPY", cabin: "Economy", discount: 46, seatsRemaining: 30 },
        { origin: "東京", originCode: "NRT", destination: "ドバイ", destinationCode: "DXB", price: 298000, originalPrice: 520000, currency: "JPY", cabin: "Business", discount: 43 },
        { origin: "大阪", originCode: "KIX", destination: "ドバイ", destinationCode: "DXB", price: 72000, originalPrice: 130000, currency: "JPY", cabin: "Economy", discount: 45 },
      ],
      sourceUrl: "https://www.emirates.com/jp/japanese/special-offers/",
      scrapedAt: new Date().toISOString(),
      isActive: true,
    },
  ],
  SQ: [
    {
      id: "sia-early-bird-2026-05",
      airlineCode: "SQ",
      airlineName: "シンガポール航空",
      saleName: "早期予約割引キャンペーン",
      description: "60日前までの予約でシンガポール線が割引。",
      startDate: "2026-05-01",
      endDate: "2026-05-31",
      bookingDeadline: "2026-05-31",
      travelPeriodStart: "2026-07-01",
      travelPeriodEnd: "2026-11-30",
      routes: [
        { origin: "東京", originCode: "NRT", destination: "シンガポール", destinationCode: "SIN", price: 58000, originalPrice: 98000, currency: "JPY", cabin: "Economy", discount: 41 },
        { origin: "東京", originCode: "HND", destination: "シンガポール", destinationCode: "SIN", price: 215000, originalPrice: 380000, currency: "JPY", cabin: "Business", discount: 43 },
        { origin: "大阪", originCode: "KIX", destination: "シンガポール", destinationCode: "SIN", price: 55000, originalPrice: 95000, currency: "JPY", cabin: "Economy", discount: 42 },
      ],
      sourceUrl: "https://www.singaporeair.com/en_UK/jp/special-offers/",
      scrapedAt: new Date().toISOString(),
      isActive: true,
    },
  ],
  CX: [
    {
      id: "cathay-summer-2026-05",
      airlineCode: "CX",
      airlineName: "キャセイパシフィック航空",
      saleName: "キャセイ サマーセール",
      description: "夏の香港・東南アジア路線がお得。エコノミー＆ビジネス対象。",
      startDate: "2026-05-12",
      endDate: "2026-06-15",
      bookingDeadline: "2026-06-15",
      travelPeriodStart: "2026-07-01",
      travelPeriodEnd: "2026-09-30",
      routes: [
        { origin: "東京", originCode: "NRT", destination: "香港", destinationCode: "HKG", price: 38000, originalPrice: 68000, currency: "JPY", cabin: "Economy", discount: 44, seatsRemaining: 15 },
        { origin: "大阪", originCode: "KIX", destination: "香港", destinationCode: "HKG", price: 35000, originalPrice: 65000, currency: "JPY", cabin: "Economy", discount: 46 },
      ],
      sourceUrl: "https://www.cathaypacific.com/cx/ja_JP/special-offers.html",
      scrapedAt: new Date().toISOString(),
      isActive: true,
    },
  ],
  APJ: [
    {
      id: "spring-flash-2026-05",
      airlineCode: "APJ",
      airlineName: "Spring Japan",
      saleName: "Spring 片道キャンペーン",
      description: "中国路線片道が驚きの価格。成田発全路線対象。",
      startDate: "2026-05-13",
      endDate: "2026-05-30",
      bookingDeadline: "2026-05-30",
      travelPeriodStart: "2026-06-15",
      travelPeriodEnd: "2026-08-31",
      routes: [
        { origin: "東京", originCode: "NRT", destination: "上海", destinationCode: "PVG", price: 8800, originalPrice: 25000, currency: "JPY", cabin: "Economy", discount: 65, seatsRemaining: 18 },
        { origin: "東京", originCode: "NRT", destination: "ハルビン", destinationCode: "HRB", price: 9900, originalPrice: 28000, currency: "JPY", cabin: "Economy", discount: 65 },
        { origin: "東京", originCode: "NRT", destination: "広島", destinationCode: "HIJ", price: 3980, originalPrice: 18000, currency: "JPY", cabin: "Economy", discount: 78, seatsRemaining: 12 },
      ],
      sourceUrl: "https://jp.ch.com/campaign",
      scrapedAt: new Date().toISOString(),
      isActive: true,
    },
  ],
  TW: [
    {
      id: "tway-happy-2026-05",
      airlineCode: "TW",
      airlineName: "ティーウェイ航空",
      saleName: "T'way ハッピーセール",
      description: "韓国路線が全便対象のハッピーセール。福岡・大阪・成田発。",
      startDate: "2026-05-11",
      endDate: "2026-05-20",
      bookingDeadline: "2026-05-20",
      travelPeriodStart: "2026-06-01",
      travelPeriodEnd: "2026-07-31",
      routes: [
        { origin: "福岡", originCode: "FUK", destination: "ソウル", destinationCode: "ICN", price: 6900, originalPrice: 18000, currency: "JPY", cabin: "Economy", discount: 62, seatsRemaining: 10 },
        { origin: "大阪", originCode: "KIX", destination: "ソウル", destinationCode: "ICN", price: 7500, originalPrice: 19000, currency: "JPY", cabin: "Economy", discount: 61 },
      ],
      sourceUrl: "https://www.twayair.com/promotion",
      scrapedAt: new Date().toISOString(),
      isActive: true,
    },
  ],
  VJ: [
    {
      id: "vietjet-sky-2026-05",
      airlineCode: "VJ",
      airlineName: "ベトジェットエア",
      saleName: "SKY SALE 全路線0円〜",
      description: "ベトナム全路線＆日本国内路線が対象のフラッシュセール。",
      startDate: "2026-05-14",
      endDate: "2026-05-15",
      bookingDeadline: "2026-05-15",
      travelPeriodStart: "2026-06-01",
      travelPeriodEnd: "2026-07-15",
      routes: [
        { origin: "名古屋", originCode: "NGO", destination: "ホーチミン", destinationCode: "SGN", price: 12800, originalPrice: 28000, currency: "JPY", cabin: "Economy", discount: 54, seatsRemaining: 2 },
        { origin: "東京", originCode: "NRT", destination: "ハノイ", destinationCode: "HAN", price: 9800, originalPrice: 25000, currency: "JPY", cabin: "Economy", discount: 61, seatsRemaining: 5 },
      ],
      sourceUrl: "https://www.vietjetair.com/promotion",
      scrapedAt: new Date().toISOString(),
      isActive: true,
    },
  ],
};

export class MockScraper extends AirlineScraper {
  protected async fetchSales(): Promise<AirlineSale[]> {
    await new Promise((r) => setTimeout(r, 100));
    return MOCK_SALES_DB[this.airlineCode] ?? [];
  }
}
